version: '3'
services:
  slc-api:    
    build: 
      context: .
    image: dynamikarray/slcstreamdvr:latest
    networks:
      - slc-dvr
    depends_on:
      - mongo   
    ports:
      - "3000:3000"

  ## MONDO DB ##
  mongo:
    container_name: mongodb
    restart: always
    image: mongo    
    volumes:
      - ~/mongo/data:/slcApps/data/db
    ports:
      - '27017:27017'
    networks:
      - slc-dvr

networks:
  slc-dvr:
    driver: bridge
