version: '3'
services:
  slc-api:    
    build: 
      context: .
    image: dynamikarray/slcstreamdvr-api:latest
    networks:
      - slc-dvr
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
    depends_on:
      - mongo   
      - redis   

  slc-worker:    
    build: 
      context: .
    image: dynamikarray/slcstreamdvr-worker:latest
    volumes:
      - C:\Development\slcStreamDVR\worker:/slcApps/src/worker
    environment:
      - DISPLAY=${DISPLAY}        
    networks:
      - slc-dvr
    links:
      - mongo
      - redis
      - slc-api
    depends_on:
      - mongo   
      - redis
      - slc-api    
    

  ## MONDO DB ##
  mongo:
    container_name: mongo
    restart: always
    image: mongo    
    volumes:
      - ~/mongo/data:/slcApps/data/db
    ports:
      - "27017:27017"
    networks:
      - slc-dvr

  ## REDIS FOR BULL QUEUE ##
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - slc-dvr

networks:
  slc-dvr:
    driver: bridge
