version: '3'
services:
  slc-api:
    build: ./api
    command: npm run dev
    volumes:
      - type: bind
        source: ./api
        target: /slcApps/src/api
    working_dir: /slcApps/src/api      
    networks:
      - slc-dvr
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
    depends_on:
      - mongo   
      - redis    

  slc-worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - ./recordings:/slcApps/recordings
      - type: bind
        source: ./worker
        target: /slcApps/src/worker           
    working_dir: /slcApps/src/worker
    environment:
      - DISPLAY=${DISPLAY}    
    networks:
      - slc-dvr
    links:
      - mongo
      - redis
      - slc-api
    depends_on:
      - mongo   
      - redis
      - slc-api  

volumes:
  recordings:
    driver: local
